backend:
  name: git-gateway
  branch: master

# publish_mode: editorial_workflow

media_folder: 'wiki/media'
public_folder: '../media'

collections:
  - name: 'characters' # Used in routes, e.g., /admin/collections/[name]
    label: 'Characters'
    label_singular: 'Character'
    description: 'Notable characters of the land'
    folder: 'wiki/characters'
    create: true
    delete: false
    extension: 'md'
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Category',
          name: 'category',
          widget: 'hidden',
          default: 'Characters',
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          default: 'Placeholder',
          required: true,
        }
    editor:
      preview: false
  - name: 'classes' # Used in routes, e.g., /admin/collections/[name]
    label: 'Classes'
    label_singular: 'Class'
    description: 'Various classes and their unique abilities'
    folder: 'wiki/classes'
    create: true
    delete: false
    extension: 'md'
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Category',
          name: 'category',
          widget: 'hidden',
          default: 'Classes',
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          default: 'Placeholder',
          required: true,
        }
    editor:
      preview: false
  - name: 'factions' # Used in routes, e.g., /admin/collections/[name]
    label: 'Factions'
    label_singular: 'Faction'
    description: 'Various organizations and groups united for shared goals'
    folder: 'wiki/factions'
    create: true
    delete: false
    extension: 'md'
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Category',
          name: 'category',
          widget: 'hidden',
          default: 'Factions',
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          default: 'Placeholder',
          required: true,
        }
    editor:
      preview: false
  - name: 'locations' # Used in routes, e.g., /admin/collections/[name]
    label: 'Locations'
    label_singular: 'Location'
    description: 'Points of interests scattered throughout Verdantia'
    folder: 'wiki/locations'
    create: true
    delete: false
    extension: 'md'
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Category',
          name: 'category',
          widget: 'hidden',
          default: 'Locations',
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          default: 'Placeholder',
          required: true,
        }
    editor:
      preview: false
  - name: 'main' # Used in routes, e.g., /admin/collections/[name]
    label: 'Main'
    label_singular: 'Main'
    description: 'Main pages for the site'
    folder: 'wiki/main'
    create: true
    delete: false
    extension: 'md'
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Category',
          name: 'category',
          widget: 'hidden',
          default: 'Main',
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          default: 'Placeholder',
          required: true,
        }
    editor:
      preview: false
  - name: 'monsters' # Used in routes, e.g., /admin/collections/[name]
    label: 'Monsters'
    label_singular: 'Monster'
    description: 'Creatures who serve only their own desire and instincts'
    folder: 'wiki/monsters'
    create: true
    delete: false
    extension: 'md'
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Category',
          name: 'category',
          widget: 'hidden',
          default: 'Monsters',
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          default: 'Placeholder',
          required: true,
        }
    editor:
      preview: false
  - name: 'races' # Used in routes, e.g., /admin/collections/[name]
    label: 'Races'
    label_singular: 'Race'
    description: 'The denizens of the realm of Verdantia'
    folder: 'wiki/races'
    create: true
    delete: false
    extension: 'md'
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Category',
          name: 'category',
          widget: 'hidden',
          default: 'Races',
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          default: 'Placeholder',
          required: true,
        }
    editor:
      preview: false
